# Generated by Django 4.0.1 on 2022-03-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_image_img_alter_profile_img'),
        ('polls', '0017_remove_image_title'),
    ]

    operations = [
    ]
