# Generated by Django 4.0.1 on 2022-03-23 15:24

import django.core.files.storage
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_merge_20220323_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/feed/', location='C:\\Users\\Harry\\Documents\\GitHub\\ECM-2434-Group-Software-Engineering-Project\\mysite\\media/feed/'), upload_to=polls.models.image_directory_path),
        ),
    ]
